# Generated by Django 2.2 on 2019-05-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('brand', '0001_initial'),
        ('product_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_method', models.CharField(blank=True, choices=[('Exclusive', 'Exclusive'), ('Inclusive', 'Inclusive')], max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('alert_quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productImages')),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_type.ProductType')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
