# Generated by Django 2.2 on 2019-06-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20190619_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='cad_type',
            field=models.CharField(blank=True, choices=[('debitCard', 'Debit Card'), ('creditCard', 'Credit Card'), ('masterCard', 'Master Card'), ('VisaCard', 'Visa Card')], default='debitCard', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payemnt_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=50, null=True),
        ),
    ]
