# Generated by Django 2.2 on 2019-06-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=30, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
            options={
                'db_table': 'sale_product_details',
            },
        ),
    ]
