# Generated by Django 2.2 on 2019-06-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('sale_product_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproductdetails',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='saleproductdetails',
            name='product_code',
        ),
        migrations.AddField(
            model_name='saleproductdetails',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
    ]
