# Generated by Django 2.2 on 2019-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='cad_type',
            field=models.CharField(blank=True, choices=[('debitCard', 'Debit Card'), ('creditCard', 'Credit Card'), ('masterCard', 'Master Card'), ('VisaCard', 'Visa Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payemnt_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
