# Generated by Django 2.2 on 2019-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190618_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
